// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataWrapper.proto

package edu.berkeley.lipstick.util;

public final class DWProto {
  private DWProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataWrapperMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes value = 1;
    boolean hasValue();
    com.google.protobuf.ByteString getValue();
    
    // required int64 timestamp = 2;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional .KeyDependencySetMsg kds = 3;
    boolean hasKds();
    DWProto.KeyDependencySetMsg getKds();
    DWProto.KeyDependencySetMsgOrBuilder getKdsOrBuilder();
  }
  public static final class DataWrapperMsg extends
      com.google.protobuf.GeneratedMessage
      implements DataWrapperMsgOrBuilder {
    // Use DataWrapperMsg.newBuilder() to construct.
    private DataWrapperMsg(Builder builder) {
      super(builder);
    }
    private DataWrapperMsg(boolean noInit) {}
    
    private static final DataWrapperMsg defaultInstance;
    public static DataWrapperMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataWrapperMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DWProto.internal_static_DataWrapperMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DWProto.internal_static_DataWrapperMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    
    // required int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional .KeyDependencySetMsg kds = 3;
    public static final int KDS_FIELD_NUMBER = 3;
    private DWProto.KeyDependencySetMsg kds_;
    public boolean hasKds() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public DWProto.KeyDependencySetMsg getKds() {
      return kds_;
    }
    public DWProto.KeyDependencySetMsgOrBuilder getKdsOrBuilder() {
      return kds_;
    }
    
    private void initFields() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      kds_ = DWProto.KeyDependencySetMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasKds()) {
        if (!getKds().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, kds_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, kds_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static DWProto.DataWrapperMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.DataWrapperMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.DataWrapperMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.DataWrapperMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.DataWrapperMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.DataWrapperMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.DataWrapperMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.DataWrapperMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.DataWrapperMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.DataWrapperMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DWProto.DataWrapperMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DWProto.DataWrapperMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DWProto.internal_static_DataWrapperMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DWProto.internal_static_DataWrapperMsg_fieldAccessorTable;
      }
      
      // Construct using DWProto.DataWrapperMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKdsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (kdsBuilder_ == null) {
          kds_ = DWProto.KeyDependencySetMsg.getDefaultInstance();
        } else {
          kdsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DWProto.DataWrapperMsg.getDescriptor();
      }
      
      public DWProto.DataWrapperMsg getDefaultInstanceForType() {
        return DWProto.DataWrapperMsg.getDefaultInstance();
      }
      
      public DWProto.DataWrapperMsg build() {
        DWProto.DataWrapperMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private DWProto.DataWrapperMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        DWProto.DataWrapperMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public DWProto.DataWrapperMsg buildPartial() {
        DWProto.DataWrapperMsg result = new DWProto.DataWrapperMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (kdsBuilder_ == null) {
          result.kds_ = kds_;
        } else {
          result.kds_ = kdsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DWProto.DataWrapperMsg) {
          return mergeFrom((DWProto.DataWrapperMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DWProto.DataWrapperMsg other) {
        if (other == DWProto.DataWrapperMsg.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasKds()) {
          mergeKds(other.getKds());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (hasKds()) {
          if (!getKds().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              DWProto.KeyDependencySetMsg.Builder subBuilder = DWProto.KeyDependencySetMsg.newBuilder();
              if (hasKds()) {
                subBuilder.mergeFrom(getKds());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setKds(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes value = 1;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      
      // required int64 timestamp = 2;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .KeyDependencySetMsg kds = 3;
      private DWProto.KeyDependencySetMsg kds_ = DWProto.KeyDependencySetMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          DWProto.KeyDependencySetMsg, DWProto.KeyDependencySetMsg.Builder, DWProto.KeyDependencySetMsgOrBuilder> kdsBuilder_;
      public boolean hasKds() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public DWProto.KeyDependencySetMsg getKds() {
        if (kdsBuilder_ == null) {
          return kds_;
        } else {
          return kdsBuilder_.getMessage();
        }
      }
      public Builder setKds(DWProto.KeyDependencySetMsg value) {
        if (kdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kds_ = value;
          onChanged();
        } else {
          kdsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setKds(
          DWProto.KeyDependencySetMsg.Builder builderForValue) {
        if (kdsBuilder_ == null) {
          kds_ = builderForValue.build();
          onChanged();
        } else {
          kdsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeKds(DWProto.KeyDependencySetMsg value) {
        if (kdsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              kds_ != DWProto.KeyDependencySetMsg.getDefaultInstance()) {
            kds_ =
              DWProto.KeyDependencySetMsg.newBuilder(kds_).mergeFrom(value).buildPartial();
          } else {
            kds_ = value;
          }
          onChanged();
        } else {
          kdsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearKds() {
        if (kdsBuilder_ == null) {
          kds_ = DWProto.KeyDependencySetMsg.getDefaultInstance();
          onChanged();
        } else {
          kdsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public DWProto.KeyDependencySetMsg.Builder getKdsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getKdsFieldBuilder().getBuilder();
      }
      public DWProto.KeyDependencySetMsgOrBuilder getKdsOrBuilder() {
        if (kdsBuilder_ != null) {
          return kdsBuilder_.getMessageOrBuilder();
        } else {
          return kds_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          DWProto.KeyDependencySetMsg, DWProto.KeyDependencySetMsg.Builder, DWProto.KeyDependencySetMsgOrBuilder> 
          getKdsFieldBuilder() {
        if (kdsBuilder_ == null) {
          kdsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              DWProto.KeyDependencySetMsg, DWProto.KeyDependencySetMsg.Builder, DWProto.KeyDependencySetMsgOrBuilder>(
                  kds_,
                  getParentForChildren(),
                  isClean());
          kds_ = null;
        }
        return kdsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:DataWrapperMsg)
    }
    
    static {
      defaultInstance = new DataWrapperMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:DataWrapperMsg)
  }
  
  public interface KeyDependencySetMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .KDSEntryMsg entries = 1;
    java.util.List<DWProto.KDSEntryMsg> 
        getEntriesList();
    DWProto.KDSEntryMsg getEntries(int index);
    int getEntriesCount();
    java.util.List<? extends DWProto.KDSEntryMsgOrBuilder> 
        getEntriesOrBuilderList();
    DWProto.KDSEntryMsgOrBuilder getEntriesOrBuilder(
        int index);
  }
  public static final class KeyDependencySetMsg extends
      com.google.protobuf.GeneratedMessage
      implements KeyDependencySetMsgOrBuilder {
    // Use KeyDependencySetMsg.newBuilder() to construct.
    private KeyDependencySetMsg(Builder builder) {
      super(builder);
    }
    private KeyDependencySetMsg(boolean noInit) {}
    
    private static final KeyDependencySetMsg defaultInstance;
    public static KeyDependencySetMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public KeyDependencySetMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DWProto.internal_static_KeyDependencySetMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DWProto.internal_static_KeyDependencySetMsg_fieldAccessorTable;
    }
    
    // repeated .KDSEntryMsg entries = 1;
    public static final int ENTRIES_FIELD_NUMBER = 1;
    private java.util.List<DWProto.KDSEntryMsg> entries_;
    public java.util.List<DWProto.KDSEntryMsg> getEntriesList() {
      return entries_;
    }
    public java.util.List<? extends DWProto.KDSEntryMsgOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    public int getEntriesCount() {
      return entries_.size();
    }
    public DWProto.KDSEntryMsg getEntries(int index) {
      return entries_.get(index);
    }
    public DWProto.KDSEntryMsgOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }
    
    private void initFields() {
      entries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getEntriesCount(); i++) {
        if (!getEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(1, entries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static DWProto.KeyDependencySetMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.KeyDependencySetMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.KeyDependencySetMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.KeyDependencySetMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DWProto.KeyDependencySetMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DWProto.KeyDependencySetMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DWProto.internal_static_KeyDependencySetMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DWProto.internal_static_KeyDependencySetMsg_fieldAccessorTable;
      }
      
      // Construct using DWProto.KeyDependencySetMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DWProto.KeyDependencySetMsg.getDescriptor();
      }
      
      public DWProto.KeyDependencySetMsg getDefaultInstanceForType() {
        return DWProto.KeyDependencySetMsg.getDefaultInstance();
      }
      
      public DWProto.KeyDependencySetMsg build() {
        DWProto.KeyDependencySetMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private DWProto.KeyDependencySetMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        DWProto.KeyDependencySetMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public DWProto.KeyDependencySetMsg buildPartial() {
        DWProto.KeyDependencySetMsg result = new DWProto.KeyDependencySetMsg(this);
        int from_bitField0_ = bitField0_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DWProto.KeyDependencySetMsg) {
          return mergeFrom((DWProto.KeyDependencySetMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DWProto.KeyDependencySetMsg other) {
        if (other == DWProto.KeyDependencySetMsg.getDefaultInstance()) return this;
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getEntriesCount(); i++) {
          if (!getEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              DWProto.KDSEntryMsg.Builder subBuilder = DWProto.KDSEntryMsg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .KDSEntryMsg entries = 1;
      private java.util.List<DWProto.KDSEntryMsg> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = new java.util.ArrayList<DWProto.KDSEntryMsg>(entries_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          DWProto.KDSEntryMsg, DWProto.KDSEntryMsg.Builder, DWProto.KDSEntryMsgOrBuilder> entriesBuilder_;
      
      public java.util.List<DWProto.KDSEntryMsg> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      public DWProto.KDSEntryMsg getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      public Builder setEntries(
          int index, DWProto.KDSEntryMsg value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setEntries(
          int index, DWProto.KDSEntryMsg.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addEntries(DWProto.KDSEntryMsg value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addEntries(
          int index, DWProto.KDSEntryMsg value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addEntries(
          DWProto.KDSEntryMsg.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addEntries(
          int index, DWProto.KDSEntryMsg.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllEntries(
          java.lang.Iterable<? extends DWProto.KDSEntryMsg> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          super.addAll(values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      public DWProto.KDSEntryMsg.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      public DWProto.KDSEntryMsgOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends DWProto.KDSEntryMsgOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      public DWProto.KDSEntryMsg.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            DWProto.KDSEntryMsg.getDefaultInstance());
      }
      public DWProto.KDSEntryMsg.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, DWProto.KDSEntryMsg.getDefaultInstance());
      }
      public java.util.List<DWProto.KDSEntryMsg.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DWProto.KDSEntryMsg, DWProto.KDSEntryMsg.Builder, DWProto.KDSEntryMsgOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DWProto.KDSEntryMsg, DWProto.KDSEntryMsg.Builder, DWProto.KDSEntryMsgOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:KeyDependencySetMsg)
    }
    
    static {
      defaultInstance = new KeyDependencySetMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:KeyDependencySetMsg)
  }
  
  public interface KDSEntryMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional .WriteClockMsg wc = 2;
    boolean hasWc();
    DWProto.WriteClockMsg getWc();
    DWProto.WriteClockMsgOrBuilder getWcOrBuilder();
  }
  public static final class KDSEntryMsg extends
      com.google.protobuf.GeneratedMessage
      implements KDSEntryMsgOrBuilder {
    // Use KDSEntryMsg.newBuilder() to construct.
    private KDSEntryMsg(Builder builder) {
      super(builder);
    }
    private KDSEntryMsg(boolean noInit) {}
    
    private static final KDSEntryMsg defaultInstance;
    public static KDSEntryMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public KDSEntryMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DWProto.internal_static_KDSEntryMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DWProto.internal_static_KDSEntryMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .WriteClockMsg wc = 2;
    public static final int WC_FIELD_NUMBER = 2;
    private DWProto.WriteClockMsg wc_;
    public boolean hasWc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public DWProto.WriteClockMsg getWc() {
      return wc_;
    }
    public DWProto.WriteClockMsgOrBuilder getWcOrBuilder() {
      return wc_;
    }
    
    private void initFields() {
      key_ = "";
      wc_ = DWProto.WriteClockMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasWc()) {
        if (!getWc().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, wc_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, wc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static DWProto.KDSEntryMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.KDSEntryMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.KDSEntryMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.KDSEntryMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.KDSEntryMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.KDSEntryMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.KDSEntryMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.KDSEntryMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.KDSEntryMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.KDSEntryMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DWProto.KDSEntryMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DWProto.KDSEntryMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DWProto.internal_static_KDSEntryMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DWProto.internal_static_KDSEntryMsg_fieldAccessorTable;
      }
      
      // Construct using DWProto.KDSEntryMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWcFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (wcBuilder_ == null) {
          wc_ = DWProto.WriteClockMsg.getDefaultInstance();
        } else {
          wcBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DWProto.KDSEntryMsg.getDescriptor();
      }
      
      public DWProto.KDSEntryMsg getDefaultInstanceForType() {
        return DWProto.KDSEntryMsg.getDefaultInstance();
      }
      
      public DWProto.KDSEntryMsg build() {
        DWProto.KDSEntryMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private DWProto.KDSEntryMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        DWProto.KDSEntryMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public DWProto.KDSEntryMsg buildPartial() {
        DWProto.KDSEntryMsg result = new DWProto.KDSEntryMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (wcBuilder_ == null) {
          result.wc_ = wc_;
        } else {
          result.wc_ = wcBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DWProto.KDSEntryMsg) {
          return mergeFrom((DWProto.KDSEntryMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DWProto.KDSEntryMsg other) {
        if (other == DWProto.KDSEntryMsg.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasWc()) {
          mergeWc(other.getWc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (hasWc()) {
          if (!getWc().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              DWProto.WriteClockMsg.Builder subBuilder = DWProto.WriteClockMsg.newBuilder();
              if (hasWc()) {
                subBuilder.mergeFrom(getWc());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setWc(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional .WriteClockMsg wc = 2;
      private DWProto.WriteClockMsg wc_ = DWProto.WriteClockMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          DWProto.WriteClockMsg, DWProto.WriteClockMsg.Builder, DWProto.WriteClockMsgOrBuilder> wcBuilder_;
      public boolean hasWc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public DWProto.WriteClockMsg getWc() {
        if (wcBuilder_ == null) {
          return wc_;
        } else {
          return wcBuilder_.getMessage();
        }
      }
      public Builder setWc(DWProto.WriteClockMsg value) {
        if (wcBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wc_ = value;
          onChanged();
        } else {
          wcBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setWc(
          DWProto.WriteClockMsg.Builder builderForValue) {
        if (wcBuilder_ == null) {
          wc_ = builderForValue.build();
          onChanged();
        } else {
          wcBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeWc(DWProto.WriteClockMsg value) {
        if (wcBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              wc_ != DWProto.WriteClockMsg.getDefaultInstance()) {
            wc_ =
              DWProto.WriteClockMsg.newBuilder(wc_).mergeFrom(value).buildPartial();
          } else {
            wc_ = value;
          }
          onChanged();
        } else {
          wcBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearWc() {
        if (wcBuilder_ == null) {
          wc_ = DWProto.WriteClockMsg.getDefaultInstance();
          onChanged();
        } else {
          wcBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public DWProto.WriteClockMsg.Builder getWcBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getWcFieldBuilder().getBuilder();
      }
      public DWProto.WriteClockMsgOrBuilder getWcOrBuilder() {
        if (wcBuilder_ != null) {
          return wcBuilder_.getMessageOrBuilder();
        } else {
          return wc_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          DWProto.WriteClockMsg, DWProto.WriteClockMsg.Builder, DWProto.WriteClockMsgOrBuilder> 
          getWcFieldBuilder() {
        if (wcBuilder_ == null) {
          wcBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              DWProto.WriteClockMsg, DWProto.WriteClockMsg.Builder, DWProto.WriteClockMsgOrBuilder>(
                  wc_,
                  getParentForChildren(),
                  isClean());
          wc_ = null;
        }
        return wcBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:KDSEntryMsg)
    }
    
    static {
      defaultInstance = new KDSEntryMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:KDSEntryMsg)
  }
  
  public interface WriteClockMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .ClockEntryMsg entries = 1;
    java.util.List<DWProto.ClockEntryMsg> 
        getEntriesList();
    DWProto.ClockEntryMsg getEntries(int index);
    int getEntriesCount();
    java.util.List<? extends DWProto.ClockEntryMsgOrBuilder> 
        getEntriesOrBuilderList();
    DWProto.ClockEntryMsgOrBuilder getEntriesOrBuilder(
        int index);
  }
  public static final class WriteClockMsg extends
      com.google.protobuf.GeneratedMessage
      implements WriteClockMsgOrBuilder {
    // Use WriteClockMsg.newBuilder() to construct.
    private WriteClockMsg(Builder builder) {
      super(builder);
    }
    private WriteClockMsg(boolean noInit) {}
    
    private static final WriteClockMsg defaultInstance;
    public static WriteClockMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public WriteClockMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DWProto.internal_static_WriteClockMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DWProto.internal_static_WriteClockMsg_fieldAccessorTable;
    }
    
    // repeated .ClockEntryMsg entries = 1;
    public static final int ENTRIES_FIELD_NUMBER = 1;
    private java.util.List<DWProto.ClockEntryMsg> entries_;
    public java.util.List<DWProto.ClockEntryMsg> getEntriesList() {
      return entries_;
    }
    public java.util.List<? extends DWProto.ClockEntryMsgOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    public int getEntriesCount() {
      return entries_.size();
    }
    public DWProto.ClockEntryMsg getEntries(int index) {
      return entries_.get(index);
    }
    public DWProto.ClockEntryMsgOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }
    
    private void initFields() {
      entries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getEntriesCount(); i++) {
        if (!getEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(1, entries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static DWProto.WriteClockMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.WriteClockMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.WriteClockMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.WriteClockMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.WriteClockMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.WriteClockMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.WriteClockMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.WriteClockMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.WriteClockMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.WriteClockMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DWProto.WriteClockMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DWProto.WriteClockMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DWProto.internal_static_WriteClockMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DWProto.internal_static_WriteClockMsg_fieldAccessorTable;
      }
      
      // Construct using DWProto.WriteClockMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DWProto.WriteClockMsg.getDescriptor();
      }
      
      public DWProto.WriteClockMsg getDefaultInstanceForType() {
        return DWProto.WriteClockMsg.getDefaultInstance();
      }
      
      public DWProto.WriteClockMsg build() {
        DWProto.WriteClockMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private DWProto.WriteClockMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        DWProto.WriteClockMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public DWProto.WriteClockMsg buildPartial() {
        DWProto.WriteClockMsg result = new DWProto.WriteClockMsg(this);
        int from_bitField0_ = bitField0_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DWProto.WriteClockMsg) {
          return mergeFrom((DWProto.WriteClockMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DWProto.WriteClockMsg other) {
        if (other == DWProto.WriteClockMsg.getDefaultInstance()) return this;
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getEntriesCount(); i++) {
          if (!getEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              DWProto.ClockEntryMsg.Builder subBuilder = DWProto.ClockEntryMsg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .ClockEntryMsg entries = 1;
      private java.util.List<DWProto.ClockEntryMsg> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entries_ = new java.util.ArrayList<DWProto.ClockEntryMsg>(entries_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          DWProto.ClockEntryMsg, DWProto.ClockEntryMsg.Builder, DWProto.ClockEntryMsgOrBuilder> entriesBuilder_;
      
      public java.util.List<DWProto.ClockEntryMsg> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      public DWProto.ClockEntryMsg getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      public Builder setEntries(
          int index, DWProto.ClockEntryMsg value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setEntries(
          int index, DWProto.ClockEntryMsg.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addEntries(DWProto.ClockEntryMsg value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addEntries(
          int index, DWProto.ClockEntryMsg value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addEntries(
          DWProto.ClockEntryMsg.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addEntries(
          int index, DWProto.ClockEntryMsg.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllEntries(
          java.lang.Iterable<? extends DWProto.ClockEntryMsg> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          super.addAll(values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      public DWProto.ClockEntryMsg.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      public DWProto.ClockEntryMsgOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends DWProto.ClockEntryMsgOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      public DWProto.ClockEntryMsg.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            DWProto.ClockEntryMsg.getDefaultInstance());
      }
      public DWProto.ClockEntryMsg.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, DWProto.ClockEntryMsg.getDefaultInstance());
      }
      public java.util.List<DWProto.ClockEntryMsg.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DWProto.ClockEntryMsg, DWProto.ClockEntryMsg.Builder, DWProto.ClockEntryMsgOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DWProto.ClockEntryMsg, DWProto.ClockEntryMsg.Builder, DWProto.ClockEntryMsgOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:WriteClockMsg)
    }
    
    static {
      defaultInstance = new WriteClockMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:WriteClockMsg)
  }
  
  public interface ClockEntryMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string writer = 1;
    boolean hasWriter();
    String getWriter();
    
    // required int64 value = 2;
    boolean hasValue();
    long getValue();
  }
  public static final class ClockEntryMsg extends
      com.google.protobuf.GeneratedMessage
      implements ClockEntryMsgOrBuilder {
    // Use ClockEntryMsg.newBuilder() to construct.
    private ClockEntryMsg(Builder builder) {
      super(builder);
    }
    private ClockEntryMsg(boolean noInit) {}
    
    private static final ClockEntryMsg defaultInstance;
    public static ClockEntryMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClockEntryMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DWProto.internal_static_ClockEntryMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DWProto.internal_static_ClockEntryMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string writer = 1;
    public static final int WRITER_FIELD_NUMBER = 1;
    private java.lang.Object writer_;
    public boolean hasWriter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getWriter() {
      java.lang.Object ref = writer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          writer_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWriterBytes() {
      java.lang.Object ref = writer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        writer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private long value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getValue() {
      return value_;
    }
    
    private void initFields() {
      writer_ = "";
      value_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasWriter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getWriterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getWriterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static DWProto.ClockEntryMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.ClockEntryMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.ClockEntryMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static DWProto.ClockEntryMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.ClockEntryMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.ClockEntryMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static DWProto.ClockEntryMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.ClockEntryMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static DWProto.ClockEntryMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static DWProto.ClockEntryMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DWProto.ClockEntryMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DWProto.ClockEntryMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DWProto.internal_static_ClockEntryMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DWProto.internal_static_ClockEntryMsg_fieldAccessorTable;
      }
      
      // Construct using DWProto.ClockEntryMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        writer_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DWProto.ClockEntryMsg.getDescriptor();
      }
      
      public DWProto.ClockEntryMsg getDefaultInstanceForType() {
        return DWProto.ClockEntryMsg.getDefaultInstance();
      }
      
      public DWProto.ClockEntryMsg build() {
        DWProto.ClockEntryMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private DWProto.ClockEntryMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        DWProto.ClockEntryMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public DWProto.ClockEntryMsg buildPartial() {
        DWProto.ClockEntryMsg result = new DWProto.ClockEntryMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.writer_ = writer_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DWProto.ClockEntryMsg) {
          return mergeFrom((DWProto.ClockEntryMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(DWProto.ClockEntryMsg other) {
        if (other == DWProto.ClockEntryMsg.getDefaultInstance()) return this;
        if (other.hasWriter()) {
          setWriter(other.getWriter());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasWriter()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              writer_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string writer = 1;
      private java.lang.Object writer_ = "";
      public boolean hasWriter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getWriter() {
        java.lang.Object ref = writer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          writer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWriter(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        writer_ = value;
        onChanged();
        return this;
      }
      public Builder clearWriter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        writer_ = getDefaultInstance().getWriter();
        onChanged();
        return this;
      }
      void setWriter(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        writer_ = value;
        onChanged();
      }
      
      // required int64 value = 2;
      private long value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getValue() {
        return value_;
      }
      public Builder setValue(long value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ClockEntryMsg)
    }
    
    static {
      defaultInstance = new ClockEntryMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ClockEntryMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DataWrapperMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DataWrapperMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyDependencySetMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyDependencySetMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KDSEntryMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KDSEntryMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteClockMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WriteClockMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ClockEntryMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ClockEntryMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DataWrapper.proto\"U\n\016DataWrapperMsg\022\r\n" +
      "\005value\030\001 \002(\014\022\021\n\ttimestamp\030\002 \002(\003\022!\n\003kds\030\003" +
      " \001(\0132\024.KeyDependencySetMsg\"4\n\023KeyDepende" +
      "ncySetMsg\022\035\n\007entries\030\001 \003(\0132\014.KDSEntryMsg" +
      "\"6\n\013KDSEntryMsg\022\013\n\003key\030\001 \002(\t\022\032\n\002wc\030\002 \001(\013" +
      "2\016.WriteClockMsg\"0\n\rWriteClockMsg\022\037\n\007ent" +
      "ries\030\001 \003(\0132\016.ClockEntryMsg\".\n\rClockEntry" +
      "Msg\022\016\n\006writer\030\001 \002(\t\022\r\n\005value\030\002 \002(\003B\tB\007DW" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DataWrapperMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DataWrapperMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DataWrapperMsg_descriptor,
              new java.lang.String[] { "Value", "Timestamp", "Kds", },
              DWProto.DataWrapperMsg.class,
              DWProto.DataWrapperMsg.Builder.class);
          internal_static_KeyDependencySetMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_KeyDependencySetMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KeyDependencySetMsg_descriptor,
              new java.lang.String[] { "Entries", },
              DWProto.KeyDependencySetMsg.class,
              DWProto.KeyDependencySetMsg.Builder.class);
          internal_static_KDSEntryMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_KDSEntryMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KDSEntryMsg_descriptor,
              new java.lang.String[] { "Key", "Wc", },
              DWProto.KDSEntryMsg.class,
              DWProto.KDSEntryMsg.Builder.class);
          internal_static_WriteClockMsg_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_WriteClockMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WriteClockMsg_descriptor,
              new java.lang.String[] { "Entries", },
              DWProto.WriteClockMsg.class,
              DWProto.WriteClockMsg.Builder.class);
          internal_static_ClockEntryMsg_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ClockEntryMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ClockEntryMsg_descriptor,
              new java.lang.String[] { "Writer", "Value", },
              DWProto.ClockEntryMsg.class,
              DWProto.ClockEntryMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
